name: Deploy to AWS EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.EC2_SSH_KEY }}

      - name: Deploy Docker container on EC2
        run: |
          ssh ubuntu@3.83.8.60 <<EOF
            cd /home/ubuntu/IDCardFrontend
            git pull origin main
            sudo docker-compose down
            sudo docker-compose up -d --build
          EOF
