name: Deploy to AWS EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Disable SSH Host Key Checking
        run: echo "StrictHostKeyChecking no" >> ~/.ssh/config

      - name: Add EC2 Host to Known Hosts
        run: ssh-keyscan -H ${{ secrets.AWS_EC2_IP_ADDRESS }} >> ~/.ssh/known_hosts

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.EC2_SSH_KEY }}

      - name: Deploy Docker container on EC2
        run: |
          ssh ubuntu@${{ secrets.AWS_EC2_IP_ADDRESS }} <<EOF
            cd /home/ubuntu/IDCardFrontend
            git pull origin main
            sudo docker-compose down
            sudo docker-compose up -d --build
          EOF
